language: python

matrix:
  include:
    - name: "Python 3.9 (Xenial Linux)"
      language: python
      dist: xenial
      python: 3.9
      before_install:
        - python -m pip install --upgrade pip
      install:
        - python -m pip install -r src/requirements-develop.txt
      script: make test

after_success:
  - codecov
notifications:
  email:
    - hayesall@iu.edu
