sudo: false
language: python

matrix:
  include:
    - name: "Python 3.7 (Xenial Linux)"
      language: python
      dist: xenial
      python: 3.7
      install:
        - pip install -r src/requirements-develop.txt
      script: make test

after_success:
  - codecov
notifications:
  email:
    - hayesall@iu.edu
